version: 0.0
os: linux

files:
  - source: app/s/
    destination: /var/www/podcast-land
  - source: infrastructure/dev/podcast-land.conf
    destination: /etc/nginx/sites-available

permissions:
  - object: /var/www/html
    pattern: newpage.html
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/configure-nginx.sh
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/webserver-start.sh
